LibraryAppPazarama/LibraryAppPazarama/Models/ErrorViewModel.cs
using System;

namespace LibraryAppPazarama.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

LibraryAppPazarama/LibraryAppPazarama/Controllers/BooksController.cs
using LibraryAppPazarama.Data;
using LibraryAppPazarama.Entity;
using LibraryAppPazarama.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryAppPazarama.Controllers
{
    public class BooksController : Controller
    {
        private readonly LibraryDbContext _context;
        public BooksController(LibraryDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult List(int? id, string q)
        {
            var books = _context.Books.AsQueryable();

            if (id != null)
            {
                books = books
                    .Include(m => m.Genres)
                    .Where(m => m.Genres.Any(g => g.GenreId == id));
            }

            if (!string.IsNullOrEmpty(q))
            {
                books = books.Where(i =>
                    i.Title.ToLower().Contains(q.ToLower()) ||
                    i.Description.ToLower().Contains(q.ToLower()));
            }

            var model = new BooksViewModel()
            {
                Books = books.ToList()
            };

            return View("Books", model);
        }
        [HttpGet]
        public IActionResult Details(int id)
        {
            return View(_context.Books.Find(id));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            return View(_context.Books.Find(id));
        }

        [HttpPost]
        public IActionResult Edit(Books m)
        {

            _context.Books.Update(m);
            _context.SaveChanges();
            return RedirectToAction("List", "Books", new { @id = m.BookId });
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Books m)
        {
            _context.Books.Add(m);
            _context.SaveChanges();
            TempData["Message"] = $"{m.Title} isimli kitap eklendi.";
            return RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult Delete(int BookId, string Title)
        {
            var entity = _context.Books.Find(BookId);
            _context.Books.Remove(entity);
            _context.SaveChanges();
            TempData["Message"] = $"{Title} isimli kitap silindi.";
            return RedirectToAction("List");
        }

    }
}

LibraryAppPazarama/LibraryAppPazarama/Controllers/HomeController.cs
using LibraryAppPazarama.Data;
using LibraryAppPazarama.Models;
using LibraryAppPazarama.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryAppPazarama.Controllers
{
    public class HomeController : Controller
    {

        private readonly LibraryDbContext _context;

        public HomeController(LibraryDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {


            var model = new HomePageViewModel
            {
                PopularBooks = _context.Books.ToList()
            };
            return View(model);
        }

        public IActionResult Privacy()
        {
            return View();
        }


    }
}

LibraryAppPazarama/LibraryAppPazarama/ViewComponents/GenresViewComponent.cs
using LibraryAppPazarama.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryAppPazarama.ViewComponents
{
    public class GenresViewComponent : ViewComponent
    {
        private readonly LibraryDbContext _context;
        public GenresViewComponent(LibraryDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedGenre = RouteData.Values["id"];
            return View(_context.Genres.ToList());
        }

    }
}

LibraryAppPazarama/LibraryAppPazarama/Views/Books/Books.cshtml
@model BooksViewModel
<h1> Kitap Listesi</h1>

<div id="kitaplar">
    @if (Model.Books.Count > 0)
    {
        @foreach (var book in Model.Books)
        {
            @await Html.PartialAsync("_book", book)
        }
    }
    else
    {
        <div class="alert alert-danger">Kitap bulunamadı</div>
    }
</div>

@section menu
{
    @await Component.InvokeAsync("Genres")
}

LibraryAppPazarama/LibraryAppPazarama/Views/Books/Create.cshtml
@model LibraryAppPazarama.Entity.Books

@{
    ViewData["Title"] = "Create";
}
<div>

    <h1>Create</h1>

    <h4>Kitaplar</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Title" class="control-label"></label>
                    <input asp-for="Title" class="form-control" />
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description" class="control-label"></label>
                    <input asp-for="Description" class="form-control" />
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl" class="control-label"></label>
                    <input asp-for="ImageUrl" class="form-control" />
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="List">Listeye dön</a>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

LibraryAppPazarama/LibraryAppPazarama/Views/Books/Details.cshtml
@model LibraryAppPazarama.Entity.Books

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Kitap</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BookId">Düzenle</a> |
    <a asp-action="List">Listeye Dön</a>
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Books/Edit.cshtml
@model Books

<div>
    <h1>Kitap Düzenle</h1>

    <div>
        <form method="post" asp-controller="Books" asp-action="Edit">
            <input type="hidden" name="BookId" value="@Model.BookId" />
            <div class="form-group">
                <label asp-for="Title"></label>
                <input asp-for="Title" class="form-control" value="@Model.Title" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" class="form-control">@Model.Description</textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl"></label>
                <input asp-for="ImageUrl" class="form-control" value="@Model.ImageUrl" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-primary">Güncelle</button>
        </form>
    </div>
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Books/Index.cshtml
@model HomePageViewModel


@section header
{
    @await Html.PartialAsync("_header")
}
@section scripts {
    <script src="~/js/script.js"></script>
}


<h1>Kitap Listesi</h1>
<div id="kitaplar">
    @foreach (var books in Model.PopularBooks)
    {
        @await Html.PartialAsync("_books", books)
    }
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Home/Index.cshtml
@model HomePageViewModel
@section header
{
    @await Html.PartialAsync("_header");
}

<h1>Popüler Kitaplar</h1>
<div id="kitaplar">
    @foreach (var book in Model.PopularBooks)
    {
        @await Html.PartialAsync("_book", book)
    }
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/Components/Genres/Default.cshtml
@model List<Genre>
<div class="list-group">
    <a href="/books/list" class="list-group-item list-group-item-action @(ViewBag.SelectedGenre==null?"active":"")">Tüm Kategoriler</a>
    @foreach(var genre in Model)
            {
                <a href="/books/list/@genre.GenreId" class="list-group-item list-group-item-action @(ViewBag.SelectedGenre==genre.GenreId.ToString()?"active":"")">
                    @genre.Name
                </a>
            }
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pazarama Kütüphane</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @RenderSection("message", false)
    @await Html.PartialAsync("_navbar")
    @RenderSection("header", false)


    <div class="container mt-3">
        @if (IsSectionDefined("menu"))
        {
            <div class="row">
                <div class="col-md-3">
                    @RenderSection("menu", false)
                </div>
                <div class="col-md-9">
                    @RenderBody()
                </div>
            </div>
        }
        else
        {
            <div class="row">
                <div class="col-md-12"></div>
                @RenderBody()
            </div>
        }

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pazarama Kütüphane - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/_book.cshtml
@model Books
<div class="card mb-3">
    <div class="row">
        <div class="col-md-3">
            <img src="/img/@Model.ImageUrl" alt="@Model.Title" class="img-fluid" />
        </div>
        <div class="col-md-9">
            <div class="card-body">
                <h5 class="card-title">@Model.Title</h5>
                <div>
                    <a class="btn btn-primary" asp-controller="Books" asp-action="Details" asp-route-id="@Model.BookId">Detaya Git</a>

                    <a class="btn btn-warning" asp-controller="Books" asp-action="Edit" asp-route-id="@Model.BookId">Düzenle </a>
                    <form asp-controller="Books" asp-action="Delete" method="post" style="display:inline;">
                        <input type="hidden" name="Title" value="@Model.Title" />
                        <input type="hidden" name="BookId" value="@Model.BookId" />
                        <button type="submit" class="btn btn-danger">Sil</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/_header.cshtml
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Kitaplar</h1>
        <p class="lead">Liste</p>
    </div>
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/_menu.cshtml
@model List<Genre>
<div class="list-group">
    @foreach(var genre in Model)
            {
                <a href="#" class="list-group-item list-group-item-action">@genre.Name</a>
            }
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/_message.cshtml
@model String
<div class="alert alert-success mb-0 text-center">
    @Model
</div>

LibraryAppPazarama/LibraryAppPazarama/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggler">
            <a href="/" class="navbar-brand">Pazarama Kütüphane</a>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="/books/list" class="nav-link">Kitaplar</a>
                </li>

                <li class="nav-item">
                    <a href="/books/Create" class="nav-link">Kitap Ekle</a>
                </li>
            </ul>


            <form action="/books/list" method="get" class="form-inline">
                <input type="text" name="q" placeholder="Kitap Ara" class="form-control mr-2" />
                <button type="submit" class="btn btn-outline-light mr-0">Ara</button>
            </form>
        </div>
    </div>
</nav>